import { css } from "@emotion/react";

export const MyLikeCPMainStyle = (isPc) => css({
    width: "100%",
    height: "100%",
    overflowY: "scroll",
    zIndex: "996",
    fontSize: "2.2rem",
    fontWeight: "700",
    marginBottom: "2rem",
    display: "flex",
    flexDirection: "column",
    marginBottom: "3rem",
    padding: "1rem 3rem",
    borderRadius: "30px",
    border: "1px solid var(--food-gray-3)",
    width: "100%",
    width: "100%",
    fontSize: "0.7rem",
    color: "var(--food-gray-5)",
    borderTop: "1px solid var(--food-gray-2)",
    fontFamily: ""Noto Sans KR", sans-serif",
    paddingBottom: "2rem",
    display: "flex",
    justifyContent: "space-between",
    padding: "0.5rem 0",
    borderBottom: "1px solid var(--food-gray-2)",
    color: "var(--food-gray-4)",
    gap: "1rem",
    fontWeight: "600",
    flex: "0.15",
    textAlign: "center",
    flex: "0.2",
    textAlign: "center",
    flex: "1 1 0%",
    maxWidth: "100%",
    textAlign: "center",
    padding: "2rem 0",
    borderBottom: "1px solid var(--food-gray-2)",
    width: "100%",
    marginBottom: "0.5rem",
    padding: "0.4rem 0",
    fontWeight: "600",
    fontSize: "1.2rem",
    display: "inline-block",
    width: "56px",
    fontSize: "0.75rem",
    padding: "0.3rem 0",
    lineHeight: "1.6",
    textAlign: "center",
    color: "var(--food-gray-0)",
    borderRadius: "16px",
    color: "var(--food-gray-5)",
    fontSize: "0.75rem",
    lineHeight: "1.5",
    color: "var(--food-gray-5)",
    fontSize: "0.75rem",
    marginTop: "1rem",
    color: "var(--food-gray-5)",
    fontSize: "0.75rem",
    marginTop: "0.5rem",
    paddingRight: "0.5rem",
    color: "orange",
    "padding: $": {

    },
    "& > h2": {
        fontSize: "2.2rem",
        fontWeight: "700",
        marginBottom: "2rem",
    },
    "& > li": {
        display: "flex",
        justifyContent: "space-between",
        padding: "0.5rem 0",
        borderBottom: "1px solid var(--food-gray-2)",
        color: "var(--food-gray-4)",
        gap: "1rem",
    },
    "& > li > span:nth-child(1)": {
        fontWeight: "600",
        flex: "0.15",
        textAlign: "center",
    },
    "& > li > span:nth-child(2),
        & > li > span:nth-child(3)": {
        flex: "0.2",
        textAlign: "center",
    },
    "& > li > span:nth-child(4)": {
        flex: "1 1 0%",
        maxWidth: "100%",
        textAlign: "center",
    },
    "& > p:nth-child(1)": {
        marginBottom: "0.5rem",
    },
    "& > p:nth-child(1) > span:nth-child(1)": {
        padding: "0.4rem 0",
        fontWeight: "600",
        fontSize: "1.2rem",
    },
    "& > p:nth-child(1) > span:nth-child(2)": {
        display: "inline-block",
        width: "56px",
        fontSize: "0.75rem",
        padding: "0.3rem 0",
        lineHeight: "1.6",
        textAlign: "center",
        color: "var(--food-gray-0)",
        borderRadius: "16px",
    },
    "& > p:nth-child(2)": {
        color: "var(--food-gray-5)",
        fontSize: "0.75rem",
        lineHeight: "1.5",
    },
    "& > p:nth-child(3)": {
        color: "var(--food-gray-5)",
        fontSize: "0.75rem",
        marginTop: "1rem",
    },
    "& > p:nth-child(4)": {
        color: "var(--food-gray-5)",
        fontSize: "0.75rem",
        marginTop: "0.5rem",
    },
    "& .icon": {
        paddingRight: "0.5rem",
        color: "orange",
    },
    ...(!isPc && {
    padding: "0rem 1.5rem",
    "&": {
        padding: "0rem 1.5rem",
    },
    }),
});
