export const recordMockup = [
  {
    date: "2026-08-13",
    thumbnailUrl: "https://placehold.co/60?text=1",
    weatherSummary: "32° · 습도 45%",
    routineSummary: "자외선 차단 강화 · 비타민C 앰플",
    hasConflict: false,
  },
  {
    date: "2026-08-12",
    thumbnailUrl: null,
    weatherSummary: "31° · 습도 52%",
    routineSummary: "진정 토너 · 수분 크림",
    hasConflict: true,
  },
  {
    date: "2026-08-11",
    thumbnailUrl: "https://placehold.co/60?text=3",
    weatherSummary: "30° · 습도 58%",
    routineSummary: "피지 조절 · 바하 토너",
    hasConflict: false,
  },
  {
    date: "2026-08-10",
    thumbnailUrl: "https://placehold.co/60?text=4",
    weatherSummary: "29° · 습도 61%",
    routineSummary: "약산성 클렌저 · 시카 세럼",
    hasConflict: false,
  },
  {
    date: "2026-08-09",
    thumbnailUrl: null,
    weatherSummary: "28° · 습도 66%",
    routineSummary: "보습 집중 · 세라마이드 크림",
    hasConflict: true,
  },
  {
    date: "2026-08-08",
    thumbnailUrl: "https://placehold.co/60?text=6",
    weatherSummary: "27° · 습도 71%",
    routineSummary: "모공 케어 · 클레이 팩",
    hasConflict: false,
  },
  {
    date: "2026-08-07",
    thumbnailUrl: "https://placehold.co/60?text=7",
    weatherSummary: "26° · 습도 74%",
    routineSummary: "진정 패드 · 수분 에센스",
    hasConflict: false,
  },
  {
    date: "2026-08-06",
    thumbnailUrl: null,
    weatherSummary: "25° · 습도 77%",
    routineSummary: "나이트 크림 · 립 마스크",
    hasConflict: false,
  },
  {
    date: "2026-08-05",
    thumbnailUrl: "https://placehold.co/60?text=9",
    weatherSummary: "24° · 습도 79%",
    routineSummary: "자극 완화 · 판테놀 크림",
    hasConflict: true,
  },
  {
    date: "2026-08-04",
    thumbnailUrl: "https://placehold.co/60?text=10",
    weatherSummary: "23° · 습도 72%",
    routineSummary: "톤 케어 · 나이아신아마이드 세럼",
    hasConflict: false,
  },
  {
    date: "2026-08-03",
    thumbnailUrl: null,
    weatherSummary: "22° · 습도 68%",
    routineSummary: "속보습 · 히알루론산 앰플",
    hasConflict: false,
  },
  {
    date: "2026-08-02",
    thumbnailUrl: "https://placehold.co/60?text=12",
    weatherSummary: "24° · 습도 63%",
    routineSummary: "각질 정리 · 효소 파우더",
    hasConflict: true,
  },
  {
    date: "2026-08-01",
    thumbnailUrl: "https://placehold.co/60?text=13",
    weatherSummary: "25° · 습도 59%",
    routineSummary: "산뜻 보습 · 젤 크림",
    hasConflict: false,
  },
  {
    date: "2026-07-31",
    thumbnailUrl: null,
    weatherSummary: "26° · 습도 55%",
    routineSummary: "탄력 케어 · 펩타이드 세럼",
    hasConflict: false,
  },
  {
    date: "2026-07-30",
    thumbnailUrl: "https://placehold.co/60?text=15",
    weatherSummary: "27° · 습도 50%",
    routineSummary: "마무리 진정 · 알로에 젤",
    hasConflict: false,
  },
];
